/* error.h */

#ifndef _ERROR_H_INCLUDED_
#define _ERROR_H_INCLUDED_

#define TRUE  1
#define FALSE 0

#define S_OK                         0x00000000
#define ERROR_FLAG                   0x80000000

#define ERROR_FACILITY_GENERAL       0x00010000
#define ERROR_FACILITY_SHARED_MEM    0x00020000
#define ERROR_FACILITY_SEMAPHORE     0x00030000

#define ERROR_INVALID_PARAMETERS                        (ERROR_FLAG | ERROR_FACILITY_GENERAL    | 0x0001)
#define ERROR_MEMORY                                    (ERROR_FLAG | ERROR_FACILITY_GENERAL    | 0x0002)

#define ERROR_SHARED_MEM_NAME_TOO_LONG                  (ERROR_FLAG | ERROR_FACILITY_SHARED_MEM | 0x0001)
#define ERROR_SHARED_MEM_CANNOT_CREATE_DIRECTORY        (ERROR_FLAG | ERROR_FACILITY_SHARED_MEM | 0x0002)
#define ERROR_SHARED_MEM_PATH_NOT_DIRECTORY             (ERROR_FLAG | ERROR_FACILITY_SHARED_MEM | 0x0003)
#define ERROR_SHARED_MEM_CANNOT_CREATE_PATH             (ERROR_FLAG | ERROR_FACILITY_SHARED_MEM | 0x0004)
#define ERROR_SHARED_MEM_CANNOT_CREATE_IPC_TOKEN        (ERROR_FLAG | ERROR_FACILITY_SHARED_MEM | 0x0005)
#define ERROR_SHARED_MEM_ALREADY_EXISTS                 (ERROR_FLAG | ERROR_FACILITY_SHARED_MEM | 0x0006)
#define ERROR_SHARED_MEM_DOES_NOT_EXIST                 (ERROR_FLAG | ERROR_FACILITY_SHARED_MEM | 0x0007)
#define ERROR_SHARED_MEM_INVALID_SIZE                   (ERROR_FLAG | ERROR_FACILITY_SHARED_MEM | 0x0008)
#define ERROR_SHARED_MEM_CANNOT_STAT                    (ERROR_FLAG | ERROR_FACILITY_SHARED_MEM | 0x0009)
#define ERROR_SHARED_MEM_CANNOT_OPEN                    (ERROR_FLAG | ERROR_FACILITY_SHARED_MEM | 0x000A)
#define ERROR_SHARED_MEM_CANNOT_ATTACH                  (ERROR_FLAG | ERROR_FACILITY_SHARED_MEM | 0x000B)


#define ERROR_SEMAPHORE_NAME_TOO_LONG                   (ERROR_FLAG | ERROR_FACILITY_SEMAPHORE | 0x0001)
#define ERROR_SEMAPHORE_CANNOT_CREATE_DIRECTORY         (ERROR_FLAG | ERROR_FACILITY_SEMAPHORE | 0x0002)
#define ERROR_SEMAPHORE_PATH_NOT_DIRECTORY              (ERROR_FLAG | ERROR_FACILITY_SEMAPHORE | 0x0003)
#define ERROR_SEMAPHORE_CANNOT_CREATE_PATH              (ERROR_FLAG | ERROR_FACILITY_SEMAPHORE | 0x0004)
#define ERROR_SEMAPHORE_CANNOT_CREATE_IPC_TOKEN         (ERROR_FLAG | ERROR_FACILITY_SEMAPHORE | 0x0005)
#define ERROR_SEMAPHORE_ALREADY_EXISTS                  (ERROR_FLAG | ERROR_FACILITY_SEMAPHORE | 0x0006)
#define ERROR_SEMAPHORE_DOES_NOT_EXIST                  (ERROR_FLAG | ERROR_FACILITY_SEMAPHORE | 0x0007)
#define ERROR_SEMAPHORE_INVALID_SIZE                    (ERROR_FLAG | ERROR_FACILITY_SEMAPHORE | 0x0008)
#define ERROR_SEMAPHORE_CANNOT_OPEN                     (ERROR_FLAG | ERROR_FACILITY_SEMAPHORE | 0x000A)


const char * error_message(int code);


#endif
