/* error.c */

#include "error.h"

const char * error_message(int code)
{
    switch (code)
    {
    case S_OK:                                      return "S_OK";

    case ERROR_FAIL:                                return "ERRROR_FAIL";
    case ERROR_INVALID_PARAMETERS:                  return "ERROR_INVALID_PARAMETERS";
    case ERROR_MEMORY:                              return "ERROR_MEMORY";

    case ERROR_SHARED_MEM_NAME_TOO_LONG:            return "ERROR_SHARED_MEM_NAME_TOO_LONG";
    case ERROR_SHARED_MEM_CANNOT_CREATE_DIRECTORY:  return "ERROR_SHARED_MEM_CANNOT_CREATE_DIRECTORY";
    case ERROR_SHARED_MEM_PATH_NOT_DIRECTORY:       return "ERROR_SHARED_MEM_PATH_NOT_DIRECTORY";
    case ERROR_SHARED_MEM_CANNOT_CREATE_PATH:       return "ERROR_SHARED_MEM_CANNOT_CREATE_PATH";
    case ERROR_SHARED_MEM_CANNOT_CREATE_IPC_TOKEN:  return "ERROR_SHARED_MEM_CANNOT_CREATE_IPC_TOKEN";
    case ERROR_SHARED_MEM_ALREADY_EXISTS:           return "ERROR_SHARED_MEM_ALREADY_EXISTS";
    case ERROR_SHARED_MEM_DOES_NOT_EXIST:           return "ERROR_SHARED_MEM_DOES_NOT_EXIST";
    case ERROR_SHARED_MEM_INVALID_SIZE:             return "ERROR_SHARED_MEM_INVALID_SIZE";
    case ERROR_SHARED_MEM_CANNOT_STAT:              return "ERROR_SHARED_MEM_CANNOT_STAT";
    case ERROR_SHARED_MEM_CANNOT_OPEN:              return "ERROR_SHARED_MEM_CANNOT_OPEN";
    case ERROR_SHARED_MEM_CANNOT_ATTACH:            return "ERROR_SHARED_MEM_CANNOT_ATTACH";

    case ERROR_SEMAPHORE_NAME_TOO_LONG:             return "ERROR_SEMAPHORE_NAME_TOO_LONG";
    case ERROR_SEMAPHORE_CANNOT_CREATE_DIRECTORY:   return "ERROR_SEMAPHORE_CANNOT_CREATE_DIRECTORY";
    case ERROR_SEMAPHORE_PATH_NOT_DIRECTORY:        return "ERROR_SEMAPHORE_PATH_NOT_DIRECTORY";
    case ERROR_SEMAPHORE_CANNOT_CREATE_PATH:        return "ERROR_SEMAPHORE_CANNOT_CREATE_PATH";
    case ERROR_SEMAPHORE_CANNOT_CREATE_IPC_TOKEN:   return "ERROR_SEMAPHORE_CANNOT_CREATE_IPC_TOKEN";
    case ERROR_SEMAPHORE_ALREADY_EXISTS:            return "ERROR_SEMAPHORE_ALREADY_EXISTS";
    case ERROR_SEMAPHORE_DOES_NOT_EXIST:            return "ERROR_SEMAPHORE_DOES_NOT_EXIST";
    case ERROR_SEMAPHORE_INVALID_SIZE:              return "ERROR_SEMAPHORE_INVALID_SIZE";
    case ERROR_SEMAPHORE_CANNOT_OPEN:               return "ERROR_SEMAPHORE_CANNOT_OPEN";


    }
    return "UNKNOWN_ERROR";
}
